/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.dinemore_client.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import lk.ijse.dinemore_client.connector.ProxyHandler;
import lk.ijse.dinemore_client.controller.CheffController;
import lk.ijse.dinemore_client.controller.TelOperatorController;
import lk.ijse.dinmore_common.dto.TelOperatorDTO;
import lk.ijse.dinmore_common.observer.Observer;
import lk.ijse.dinmore_common.service.custom.TelOperatorService;

/**
 *
 * @author Dell
 */
public class CheffForm extends javax.swing.JFrame implements Observer{

    private int selectedRow;
    private CheffPopup cheffPopup = new CheffPopup();
    private TelOperatorDTO dTO = new TelOperatorDTO();
    private CheffController controller = new CheffController();
    /**
     * Creates new form CheffForm
     */
    public CheffForm() {
         try {
            initComponents();
            showDate();
            showTime();
            loadAllOrders();
            tblCheff.setRowSelectionInterval(0, 0);
            selectedRow = tblCheff.getSelectedRow();
            manageTable();
            UnicastRemoteObject.exportObject(this,0);
            TelOperatorService telOperatorService = ProxyHandler.getInstance().getTelOperatorService();
            telOperatorService.register(this);
        } catch (RemoteException ex) {
            Logger.getLogger(TelephoneOperatorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TelephoneOperatorForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOrdeId = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFood = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnTakeOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCheff = new javax.swing.JTable();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblCheffId = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(69, 50, 69));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log In");
        jLabel1.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(69, 50, 69));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cheff ");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 638, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Cheff Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 81, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 56, -1, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Time  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 98, -1, 24));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Order Id");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 81, -1));

        txtOrdeId.setEditable(false);
        txtOrdeId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOrdeId.setToolTipText("");
        txtOrdeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdeIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrdeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, 350, -1));

        txtCustomerName.setEditable(false);
        txtCustomerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCustomerName.setToolTipText("");
        jPanel1.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, 350, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Customer Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, 139, 24));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Customer Contact");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 149, 24));

        txtContact.setEditable(false);
        txtContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtContact.setToolTipText("");
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 350, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Food");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 316, 149, -1));

        txtFood.setEditable(false);
        txtFood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFood.setText("Submarine");
        txtFood.setToolTipText("");
        jPanel1.add(txtFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 344, 350, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 383, 149, -1));

        txtQuantity.setEditable(false);
        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQuantity.setToolTipText("");
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 412, 346, -1));

        btnTakeOrder.setBackground(new java.awt.Color(0, 102, 51));
        btnTakeOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTakeOrder.setText("Take Order");
        btnTakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnTakeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 127, 51));

        tblCheff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cheff ID", "Order ID", "Customer Name", "Contact", "Qty", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblCheff);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 620, 192));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 207, 29));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 56, 207, 27));

        lblCheffId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCheffId.setText("1");
        jPanel1.add(lblCheffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 207, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrdeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdeIdActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void btnTakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeOrderActionPerformed
          
        try {
            int e_id = Integer.parseInt(lblCheffId.getText());
            int oid = Integer.parseInt(txtOrdeId.getText());
            String name = txtCustomerName.getText();
            int contact = Integer.parseInt(txtContact.getText());
            String food = txtFood.getText();
            int qty = Integer.parseInt(txtQuantity.getText());
            String time = lblTime.getText();
            
            
            dTO = new TelOperatorDTO(oid,time);
            System.out.println("Set Time DTO : "+dTO);
            boolean order = controller.getOrder(dTO);
            System.out.println("Run Order");
            if (order) {
                System.out.println("Complete Order");
                JOptionPane.showMessageDialog(this, "Order get...");
                 dTO = new TelOperatorDTO(oid,e_id , name, contact,food, qty, time);
                cheffPopup = new CheffPopup(dTO);
                cheffPopup.setVisible(true);
            }
            
           
        } catch (Exception ex) {
            Logger.getLogger(CheffForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTakeOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTakeOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheffId;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblCheff;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtFood;
    private javax.swing.JTextField txtOrdeId;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
private void showDate() {
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        lblDate.setText(simpleDateFormat.format(date));
    }

    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(simpleDateFormat.format(date));
            }
        }).start();
    }

    private void loadAllOrders() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblCheff.getModel();
            dtm.setRowCount(0);
            TelOperatorController controller = new TelOperatorController();
            ArrayList<TelOperatorDTO> allOrder = controller.getAllOrder();
            for (TelOperatorDTO t : allOrder) {
                Object[] row = {t.getE_id(), t.getOid(), t.getCustomer_name(), t.getCustomer_contact(), t.getQty(), t.getDate(), t.getTime()};
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(CheffForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void manageTable(){
        DefaultTableModel model = (DefaultTableModel) tblCheff.getModel();
        lblCheffId.setText(Integer.toString((int) model.getValueAt(selectedRow, 0)));
        txtOrdeId.setText(Integer.toString((int) model.getValueAt(selectedRow, 1)));
        txtCustomerName.setText((String) model.getValueAt(selectedRow, 2));
        txtContact.setText(Integer.toString((int) model.getValueAt(selectedRow, 3)));
        txtQuantity.setText(Integer.toString((int) model.getValueAt(selectedRow, 4)));
    }

    @Override
    public void update(String message) throws Exception {
        JOptionPane.showMessageDialog(this, message);
    }
}
